# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\home.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(922, 786)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 100, 831, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 40, 441, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.pushButton.clicked.connect(mainWindow.enter)
        self.pushButton_2.clicked.connect(mainWindow.enter)
        self.pushButton_3.clicked.connect(mainWindow.enter)
        self.pushButton_4.clicked.connect(mainWindow.enter)
        self.pushButton_5.clicked.connect(mainWindow.enter)
        self.pushButton_6.clicked.connect(mainWindow.chatbot)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "聊天室"))
        self.label_5.setText(_translate("mainWindow", "TextLabel"))
        self.label_8.setText(_translate("mainWindow", "学习"))
        self.label_9.setText(_translate("mainWindow", "在线人数：5人"))
        self.pushButton.setText(_translate("mainWindow", "进入"))
        self.label_6.setText(_translate("mainWindow", "TextLabel"))
        self.label_10.setText(_translate("mainWindow", "放松"))
        self.label_11.setText(_translate("mainWindow", "在线人数：10人"))
        self.pushButton_4.setText(_translate("mainWindow", "进入"))
        self.label_12.setText(_translate("mainWindow", "TextLabel"))
        self.label_13.setText(_translate("mainWindow", "心情"))
        self.label_14.setText(_translate("mainWindow", "在线人数：9人"))
        self.pushButton_2.setText(_translate("mainWindow", "进入"))
        self.label_15.setText(_translate("mainWindow", "TextLabel"))
        self.label_16.setText(_translate("mainWindow", "电影"))
        self.label_17.setText(_translate("mainWindow", "在线人数：1人"))
        self.pushButton_5.setText(_translate("mainWindow", "进入"))
        self.label_18.setText(_translate("mainWindow", "TextLabel"))
        self.label_19.setText(_translate("mainWindow", "理想"))
        self.label_20.setText(_translate("mainWindow", "在线人数：3人"))
        self.pushButton_3.setText(_translate("mainWindow", "进入"))
        self.label_21.setText(_translate("mainWindow", "TextLabel"))
        self.label_24.setText(_translate("mainWindow", "与机器人聊天"))
        self.pushButton_6.setText(_translate("mainWindow", "进入"))
        self.label_7.setText(_translate("mainWindow", "请选择你感兴趣的聊天室："))
